# connection: project:region:instance
db-config:
  host: "voda-342511:asia-northeast3:voda"
  user: "root"
  name: "voda"
  password: "voda1!"

client:
  kakao:
    base-url: "https://kapi.kakao.com"
    oauth:
      client-id: "c663ce96b79395b5dcc6d7f774e1af67"
      client-secret: "LLlLMwzJ9VjLXhjsJYx4pE3zsE1x9m4P"
      redirect-url: "https://exchange-diary-b4mzhzbzcq-du.a.run.app/v1/authentication/login/kakao"
  google:
    oauth:
      client-id: "178025470998-4n07sql4vqnpsak3ggs5jg0lnk70uh0l.apps.googleusercontent.com"
      client-secret: "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"
      redirect-url: "https://exchange-diary-b4mzhzbzcq-du.a.run.app/v1/authentication/login/google"